### ISSUE TITLE
emtyString as literal

### ISSUE THREAD

**Issue by rlzijdeman** [netwerk-digitaal-erfgoed/LDWizard-ErfgoedWizard#43] opened 2021-03-20 20:26 UTC
<img width="1222" alt="Screenshot 2021-03-20 at 21 23 55" src="https://user-images.githubusercontent.com/3480446/111884561-b8155a80-89c2-11eb-9545-3ca01ca1ff9a.png">

I got this error message:
- one after quite some time of waiting for a result -> so perhaps check this, before execution;
- I have no clue how to set this flag in LDWizard

**Comment by GerwinBosch** [comment] 2021-05-21 13:56
Duplicate of https://github.com/netwerk-digitaal-erfgoed/LDWizard/issues/66

**Closed as completed by GerwinBosch** 2021-05-21 13:56 UTC

**Comment by GerwinBosch** [comment] 2021-05-21 13:57
Thanks for the report! At the next release empty cells/literals will be skipped and shall result in a triple
